import type { Metadata } from "next";
import "./globals.css";
import { ReactQueryClientProvider } from "@/lib/config/react-query";
import { Toaster } from "@/components/ui/toaster";
import { Figtree } from "next/font/google";

export const metadata: Metadata = {
  title: "ADTO Admin Side Landing Page",
  description: "Generated by create next app",
};

const figtree = Figtree({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body className={`antialiased ${figtree.className}`}>
          <Toaster />
          <main>{children}</main>
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
