import { AppSidebar } from "@/components/layout/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { ProtectedRoute } from "@/components/auth/ProtectedRoute";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "ADTO Admin Side",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ProtectedRoute fallbackRoute="/login">
      <div className={`antialiased`}>
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full">
            <header className="flex items-center p-4 md:hidden">
              <SidebarTrigger />
            </header>
            <div className="px-4 md:px-12">{children}</div>
          </main>
        </SidebarProvider>
      </div>
    </ProtectedRoute>
  );
}
