import type { Metadata } from "next";
import "./globals.css";
import { ReactQueryClientProvider } from "@/client/react-query/react-query";


export const metadata: Metadata = {
    title: "ADTO Admin Side",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ReactQueryClientProvider>
            <body
                className={`antialiased`}
            >
                {children}
            </body>
        </ReactQueryClientProvider>
    );
}
