import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Login To ADTO Admin Side",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className={`antialiased`}>{children}</div>;
}
